### ISSUE TITLE
Need help setting up

### ISSUE THREAD

**Issue by Deat0101010** [dkopec91/SymlinkSwapper#1]
poor documentation on how to get it to work as there is no release tab to get the exe

**Comment by dkopec91** [comment]
Once you select the `Code` tab, you'll see the `Releases` section on the right-hand side of the page. It's below the `About` section. Either that or just open the following page: https://github.com/dkopec91/SymlinkSwapper/releases

The [SymlinkSwapper_v1.0.0.0.zip](https://github.com/dkopec91/SymlinkSwapper/releases/download/v1.0.0.0/SymlinkSwapper_v1.0.0.0.zip) file contains the exe.
